#!/bin/bash

# Declare an array of topics and script names
declare -A topics=(
    ["Air_Quality_Monitor"]="air_quality_monitor"
    ["Appliance_Control_Device"]="appliance_control_device"
    ["Energy_Monitoring_Device"]="energy_monitoring_device"
    ["Indoor_Climate_Monitoring_Device"]="indoor_climate_monitoring_device"
    ["Security_Device"]="security_device"
    ["Surveillance_Camera"]="surveillance_camera"
)

# Function to terminate all producer processes
terminate_all() {
    echo "Terminating all producer processes..."
    for topic in "${!topics[@]}"; do
        script_prefix="${topics[$topic]}"
        docker exec -it init-setup /bin/bash -c "pkill -f ${script_prefix}_producer.py"
    done
    echo "All producer processes terminated."
}

# Execute the termination function
terminate_all