#!/bin/bash
cd ../../Demo_CE/Topics/Air_Quality_Monitor

# Start a new tmux session for the producer
tmux new-session -d -s producer_session -n 'Producer' "python3 air_quality_monitor_producer.py > producer.log 2>&1"

# Start a new tmux session for the consumer
tmux new-session -d -s consumer_session -n 'Consumer' "python3 air_quality_monitor_consumer.py > consumer.log 2>&1"

# Attach to the producer session
tmux attach-session -t producer_session