#!/bin/bash
cd ../../Demo_CE/Topics/Air_Quality_Monitor
# Open a new terminal for the producer
gnome-terminal -- bash -c 'python3 air_quality_monitor_producer.py; exec bash'
# Open a new terminal for the consumer
gnome-terminal -- bash -c 'python3 air_quality_monitor_consumer.py; exec bash'